name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  DeployDocs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build
        run: |
          cd docs
          npm i
          npm run build
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/src/.vuepress/dist
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: yasa-org/yasa-org.github.io
          publish_branch: master

