#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  DeployDemo:
    name: Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build
        run: |
          cd yasa-ui
          npm i
          npm run build
      - name: Deploy Demo
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: yasa-ui/dist
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: yasa-org/demo
          publish_branch: master
